(function(){
 'use strict';
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const tabId=crypto.randomUUID();
 let dirty=false,baseline=null,active=false,timer,localTimer,previousFocus,opening=false,saving=false,cloudVersion=0,changeVersion=0,pendingRestore=null,recoveredDraft=null,fullscreenButton=null;
 const safeRead=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k))??fallback;}catch{return fallback;}};
 function toast(text,action){$('.ed-toast')?.remove();const el=document.createElement('div');el.className='ed-toast';el.setAttribute('role','status');el.textContent=text;if(action){const b=document.createElement('button');b.textContent=action.label;b.onclick=action.run;el.append(b);}document.body.append(el);setTimeout(()=>el.remove(),action?15000:4500);}
 function btn(text,fn,cls=''){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=cls;b.onclick=fn;return b;}
 function scope(){return `${window.auth?.currentUser?.uid||'guest'}/${new URL(location.href).searchParams.get('project')||localStorage.getItem('currentProject')||'default'}`;}
 function target(){return typeof editingId!=='undefined'&&editingId?editingId:'new';}
 function draftKey(){return `${scope()}/${target()}/${tabId}`;}
 function status(text,state=''){const el=$('#ed-save-state');if(el){el.textContent=text;el.dataset.state=state;}}
 function setEditorFullscreen(enabled){const form=$('#entry-form');if(!form)return;const active=!!enabled;form.classList.toggle('ed-fullscreen',active);document.body.classList.toggle('ed-editor-fullscreen',active);if(fullscreenButton){const label=active?'退出全屏':'全屏编辑';fullscreenButton.setAttribute('aria-label',label);fullscreenButton.setAttribute('aria-pressed',String(active));fullscreenButton.title=label;const text=fullscreenButton.querySelector('.ui-button-label');if(text)text.textContent=label;else if(!fullscreenButton.querySelector('svg,.material-icons'))fullscreenButton.textContent=label;}if(active)requestAnimationFrame(()=>form.querySelector('[contenteditable="true"]')?.focus({preventScroll:true}));}
 const dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('research-workspace',1);request.onupgradeneeded=()=>request.result.createObjectStore('drafts',{keyPath:'key'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
 dbPromise.catch(()=>{});
 async function local(action,value){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',action==='getAll'?'readonly':'readwrite');const req=tx.objectStore('drafts')[action](value);let result;req.onsuccess=()=>{result=req.result;};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);});}
 function data(){return typeof getFormData==='function'?getFormData():{};}
 function idDatePart(date){return date?.start?date.start.replaceAll('-',''):'UNDATED';}
 function idMatchesDate(id,date){const match=String(id||'').match(/^(.*)-\d+$/);return !!match&&match[1]===idDatePart(date);}
 function replaceRelationId(value,oldId,newId){
  if(Array.isArray(value))return [...new Set(value.map(id=>id===oldId?newId:id).filter(Boolean))];
  if(value&&typeof value==='object'&&Object.prototype.hasOwnProperty.call(value,oldId)){const next={...value};const linked=next[oldId];delete next[oldId];if(linked)next[newId]=linked;return next;}
  return value;
 }
 function replaceRecentId(oldId,newId){try{const pid=new URL(location.href).searchParams.get('project')||localStorage.getItem('currentProject')||'default';const key='v2_recent_'+pid;const ids=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(ids)&&ids.includes(oldId))localStorage.setItem(key,JSON.stringify([...new Set(ids.map(id=>id===oldId?newId:id))]));}catch{}}
 async function persistLocal(){if(!active||!dirty)return;try {await local('put',{key:draftKey(),scope:scope(),target:target(),data:data(),updatedAt:Date.now(),baseRevision:baseline?.revision||0,baseUpdatedAt:baseline?.updatedAt||0});status(navigator.onLine?'已保存在本机，准备同步':'已保存在本机，等待联网');return true;}catch(error){status('本机草稿保存失败，请立即保存史料或导出备份','error');return false;}}
 async function syncDraft(){if(!active||!dirty||saving)return;const localOK=await persistLocal();if(!navigator.onLine||!window.db||!window.auth?.currentUser)return localOK;const version=changeVersion,key=draftKey();status('正在同步草稿…');try{const id=`${target()}_${tabId}`;const record={...data(),updatedAt:Date.now(),originalId:target()==='new'?null:target(),draftType:target()==='new'?'new':'edit',baseRevision:baseline?.revision||0,baseUpdatedAt:baseline?.updatedAt||0};await db.ref(getProjectPath(`drafts/${id}`)).set(record);if(active&&key===draftKey()){cloudVersion=version;status(version===changeVersion?'草稿已同步 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}):'有新的修改，等待同步');}return true;}catch(error){status(localOK?'已保存在本机；云端同步失败，可重试':'草稿保存失败，请导出备份','error');return localOK;}}
 function changed(){if(!active||opening)return;dirty=true;changeVersion++;status('有未保存修改');clearTimeout(timer);clearTimeout(localTimer);localTimer=setTimeout(persistLocal,300);timer=setTimeout(syncDraft,2000);}
 async function opened(entry){opening=true;active=true;dirty=false;recoveredDraft=null;baseline=entry?JSON.parse(JSON.stringify(entry)):null;previousFocus=document.activeElement;if($('.v2-app')&&!$('.v2-app').contains($('#entry-form')))$('.v2-app').inert=true;status('修改会自动保存为草稿');$('#entry-form').setAttribute('role','dialog');$('#entry-form').setAttribute('aria-modal','true');$('#entry-form').setAttribute('aria-label',entry?'编辑史料':'新增史料');
  try{const drafts=(await local('getAll')).filter(x=>x.scope===scope()&&x.target===target()).sort((a,b)=>b.updatedAt-a.updatedAt);if(drafts.length){const recent=drafts[0];const bar=document.createElement('div');bar.className='ed-continue ed-recovery';bar.textContent=`发现本机草稿 · ${new Date(recent.updatedAt).toLocaleString()}`;bar.append(btn('恢复草稿',async()=>{recoveredDraft=recent;await populateForm(recent.data);baseline=entry?{...entry,revision:recent.baseRevision,updatedAt:recent.baseUpdatedAt??entry.updatedAt}:null;opening=false;changed();bar.remove();}),btn('忽略本次',()=>bar.remove()));$('.ed-recovery')?.remove();$('#ed-save-state').after(bar);}}catch{status('本机恢复不可用，请注意及时保存','error');}
  if(pendingRestore){const record=pendingRestore;pendingRestore=null;recoveredDraft=record;await populateForm(record.data);if(baseline)baseline={...baseline,revision:record.baseRevision||0,updatedAt:record.baseUpdatedAt??baseline.updatedAt};opening=false;changed();$('.ed-recovery')?.remove();}else opening=false;
  ResearchDates.validateAll($('#entry-form'));$('#entry-form [name="title"]')?.focus({preventScroll:true});$('#entry-form').scrollTop=0;
 }
 async function close(){if(saving)return;clearTimeout(timer);clearTimeout(localTimer);if(dirty){const ok=await persistLocal();if(!ok){toast('草稿未保存，已保留编辑窗口');return;}}active=false;dirty=false;setEditorFullscreen(false);document.querySelector('.research-comparison')?.remove();document.body.classList.remove('research-comparing');$('.ed-recovery')?.remove();if($('.v2-app'))$('.v2-app').inert=false;performCloseForm();setTimeout(()=>previousFocus?.focus(),220);}
 async function saveEntry(event){event?.preventDefault();if(saving)return;if(!$('#entry-form form').reportValidity())return;const value=data(),date=ResearchDates.parse(value.date);if(!date){toast('请填写有效日期；日期不详时可输入“不详”');return;}if(!value.title?.trim()||!value.content?.trim()){toast('请填写标题和原文内容');return;}if(!navigator.onLine){await persistLocal();status('当前离线，草稿已保留，联网后再保存史料','error');return;}
  saving=true;clearTimeout(timer);clearTimeout(localTimer);status('正在保存史料…');$('#entry-form form').inert=true;$$('#entry-form button[type="submit"]').forEach(b=>b.disabled=true);
  try{value.date=date.value;value.dateInfo=date;value.typeId=value.typeId||'general';value.metadata=value.metadata||{};value.citation=window.V2Citations?.generateCitation(value)||value.citation||'';
    const oldId=typeof editingId!=='undefined'&&editingId?editingId:null,existing=!!oldId,renaming=existing&&!idMatchesDate(oldId,date);const id=renaming?await generateID(value):(oldId||await generateID(value));const ref=db.ref(getProjectPath(`entries/${oldId||id}`));const now=Date.now(),expected=baseline?.revision||0,expectedTime=baseline?.updatedAt||0;
    const isExpected=current=>!existing||!!current&&((current.revision||0)===expected)&&((current.revision||0)>0||(current.updatedAt||0)===expectedTime);
    const buildRecord=current=>{
      const history=current?Object.values(current._history||{}):[];
      if(current){const snapshot={...current};delete snapshot._history;history.push(snapshot);}
      const preserved=current||{};
      const {commentChanges,...fields}=value;
      return {...preserved,...fields,comments:V2Comments.applyChanges(current?.comments,commentChanges),id,revision:expected+1,createdAt:current?.createdAt||now,updatedAt:now,contentFormat:'tiptap-v1',legacyBackup:current?.legacyBackup||(current&&!current.contentFormat?{content:current.content||'',analysis:current.analysis||''}:null),_history:history.slice(-10)};
    };
    let result;
    if(renaming){
      const entriesRef=db.ref(getProjectPath('entries'));
      result=await entriesRef.transaction(current=>{const all=current||{},source=all[oldId];if(!isExpected(source)||all[id])return;const next={...all};delete next[oldId];next[id]=buildRecord(source);Object.keys(next).forEach(key=>{if(key===id)return;const related=replaceRelationId(next[key]?.relatedSources,oldId,id);if(related!==next[key]?.relatedSources)next[key]={...next[key],relatedSources:related};});return next;},undefined,false);
    }else{
      await ref.once('value');
      result=await ref.transaction(current=>{if(!isExpected(current)||!existing&&current)return;return buildRecord(current);},undefined,false);
    }
    if(!result.committed){status('另一窗口已修改此史料，请先比较版本；本机草稿已保留','error');await persistLocal();toast('检测到版本冲突，未覆盖云端内容',{label:'比较版本',run:()=>conflict(ref)});return;}
    const oldKey=draftKey();dirty=false;active=false;await local('delete',oldKey).catch(()=>{});if(recoveredDraft?.key){const found=(await local('getAll')).find(r=>r.key===recoveredDraft.key);if(found?.updatedAt===recoveredDraft.updatedAt)await local('delete',recoveredDraft.key).catch(()=>{});}const cloudRecovery=recoveredDraft?.cloudId?{id:recoveredDraft.cloudId,updatedAt:recoveredDraft.data.updatedAt}:null;recoveredDraft=null;if($('.v2-app'))$('.v2-app').inert=false;
    // Failure to remove an obsolete draft must not undo a successful entry commit.
    const obsolete=[`${target()}_${tabId}`];
    Promise.allSettled(obsolete.map(key=>db.ref(getProjectPath(`drafts/${key}`)).remove()));
    if(cloudRecovery)db.ref(getProjectPath(`drafts/${cloudRecovery.id}`)).transaction(current=>current&&current.updatedAt===cloudRecovery.updatedAt?null:undefined,undefined,false).catch(()=>{});
    if(renaming)replaceRecentId(oldId,id);currentDraftId=null;entryDraft=null;editingId=null;localStorage.setItem('research-save-signal',JSON.stringify({scope:scope(),id,time:now}));setEditorFullscreen(false);performCloseForm();toast(renaming?`史料已保存，编号已更新为 ${id}`:'史料已保存');
  }catch(error){await persistLocal();status('保存失败，编辑内容已保留：'+error.message,'error');}finally{saving=false;$('#entry-form form').inert=false;$$('#entry-form button[type="submit"]').forEach(b=>b.disabled=false);}
 }
 async function conflict(ref){await loadQuillScript();const current=(await ref.once('value')).val();if(!current){toast('云端条目已删除，请复制内容后另建史料');return;}const d=ResearchHTML.dialog('版本冲突',`<p>云端已更新。请比较后选择；重新载入前，本机修改仍保存在草稿中。</p><h3>云端版本</h3><div class="ed-version-preview">${ResearchHTML.escape(current.title)}\n${ResearchHTML.escape(new DOMParser().parseFromString(current.content||'','text/html').body.textContent)}</div><h3>本机编辑</h3><div class="ed-version-preview">${ResearchHTML.escape(quill.editor.getText())}</div><div class="ed-conflict-actions"></div>`,'继续编辑',()=>{});
   d.querySelector('.ed-conflict-actions').append(btn('载入云端版本',async()=>{await persistLocal();await populateForm(current);baseline=current;dirty=false;d.close();status('已载入云端版本，本机旧修改仍可在草稿箱恢复');}),btn('保留本机内容并以云端为基准',()=>{baseline=current;dirty=true;d.close();status('已确认版本差异，请点击保存史料提交本机内容');}));
 }
 async function versions(){await loadQuillScript();if(!editingId){toast('先保存史料后即可查看历史版本');return;}const current=(await db.ref(getProjectPath(`entries/${editingId}`)).once('value')).val();const history=Object.values(current?._history||{}).reverse();const d=ResearchHTML.dialog('历史版本','<p>保留最近 10 次保存前的版本。恢复后需再次点击“保存史料”。</p><div class="ed-versions"></div><div class="ed-version-preview" hidden></div>','关闭',()=>{});const list=d.querySelector('.ed-versions');if(!history.length)list.textContent='尚无历史版本';history.forEach(v=>{const row=document.createElement('div');row.className='ed-version';row.textContent=new Date(v.updatedAt).toLocaleString();row.append(btn('预览',()=>{const el=d.querySelector('.ed-version-preview');el.hidden=false;el.textContent=v.title+'\n\n'+new DOMParser().parseFromString(v.content||'','text/html').body.textContent;}),btn('恢复到编辑区',async()=>{await persistLocal();await populateForm(v);changed();d.close();toast('历史版本已载入，请检查后保存');}));list.append(row);});}
 function exportDraft(){const blob=new Blob([JSON.stringify(data(),null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='史料草稿-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 async function restoreRecord(record){pendingRestore=record;const entry=(typeof entries!=='undefined'?entries:[]).find(e=>e.id===record.target);if(entry)await editEntry(entry.id);else{editingId=null;showForm();}}
 async function localDrafts(){await loadQuillScript();const records=(await local('getAll')).filter(x=>x.scope===scope()).sort((a,b)=>b.updatedAt-a.updatedAt);const d=ResearchHTML.dialog('本机恢复草稿','<p>这些草稿仅保存在此浏览器，按账户与课题隔离。</p><div class="ed-versions"></div>','关闭',()=>{});const list=d.querySelector('.ed-versions');if(!records.length)list.textContent='暂无本机草稿';records.forEach(r=>{const row=document.createElement('div');row.className='ed-version';const text=document.createElement('span');text.textContent=(r.data.title||'未命名史料')+' · '+new Date(r.updatedAt).toLocaleString();row.append(text,btn('恢复',()=>{d.close();restoreRecord(r);}),btn('删除',async()=>{await local('delete',r.key);row.remove();}));list.append(row);});}
 async function continueCloudDraft(id){const record=(await db.ref(getProjectPath(`drafts/${id}`)).once('value')).val();if(!record)return;if (typeof hideDraftBox === 'function') hideDraftBox();await restoreRecord({data:record,cloudId:id,target:record.originalId||'new',baseRevision:record.baseRevision||0,baseUpdatedAt:record.baseUpdatedAt});}
 async function deleteWithUndo(id){const entry=entries.find(e=>e.id===id);if(!entry)return;if(!confirm('将“'+entry.title+'”移入回收站？'))return;try{await db.ref(getProjectPath()).update({['trash/'+id]:{...entry,deletedAt:Date.now()},['entries/'+id]:null});toast('已移入回收站',{label:'撤销',run:async()=>{try{const ref=db.ref(getProjectPath('entries/'+id));await ref.once('value');const result=await ref.transaction(value=>value?undefined:entry,undefined,false);if(!result.committed){toast('条目已存在，未覆盖现有内容');return;}await db.ref(getProjectPath('trash/'+id)).remove();toast('已恢复史料');}catch(e){toast('恢复失败：'+e.message);}}});}catch(e){toast('删除失败：'+e.message);}}
 function setupEditor(){const form=$('#entry-form');if(!form)return;[['[name="title"]','ed-title-row'],['#editor-container','ed-original-row'],['#analysis-editor-container','ed-analysis-row']].forEach(([s,c])=>$(s)?.closest('.form-row')?.classList.add(c));const controls=document.createElement('div');controls.className='ed-editor-actions';fullscreenButton=btn('全屏编辑',()=>setEditorFullscreen(!form.classList.contains('ed-fullscreen')));fullscreenButton.setAttribute('aria-pressed','false');controls.append(fullscreenButton,btn('左右对照',()=>{form.classList.toggle('ed-compare');}),btn('历史版本',()=>versions().catch(e=>toast(e.message))),btn('立即同步草稿',syncDraft),btn('导出草稿备份',exportDraft));const s=document.createElement('div');s.id='ed-save-state';s.className='ed-save-state';s.setAttribute('role','status');form.querySelector('h2').after(controls,s);
  const editorForm=form.querySelector('form'),main=document.createElement('div'),meta=document.createElement('aside');main.className='ed-editor-main';meta.className='ed-editor-meta';
  [...editorForm.children].forEach(el=>{if(el.matches('.ed-title-row,.ed-original-row,.ed-analysis-row'))main.append(el);else if(!el.matches('.action-buttons'))meta.append(el);});editorForm.prepend(main,meta);
  const originalDate=document.createElement('div');originalDate.className='form-row';originalDate.innerHTML='<label for="ed-date-original">原始日期表述（可选）</label><input id="ed-date-original" name="dateOriginal" placeholder="如：民国二十六年七月七日">';meta.querySelector('[name="date"]')?.closest('.form-row').after(originalDate);
  const save=form.querySelector('button[type="submit"]');if(save){save.innerHTML='保存史料';save.classList.remove('btn-icon-only');}const closeBtn=form.querySelector('button[onclick="hideForm()"]');if(closeBtn){closeBtn.innerHTML='保存草稿并关闭';closeBtn.className='cancel-btn';}
  form.addEventListener('input',changed);form.addEventListener('change',changed);document.addEventListener('research-editor-change',changed);
  form.addEventListener('keydown',e=>{if(e.isComposing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveEntry(e);}if(e.key==='Escape'&&!document.querySelector('dialog[open]')){e.preventDefault();if(form.classList.contains('ed-fullscreen'))setEditorFullscreen(false);else close();}if(e.key==='Tab'){const list=[...form.querySelectorAll('button,input,select,textarea,[contenteditable="true"],[tabindex="0"]')].filter(x=>!x.disabled&&x.getClientRects().length);if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0]?.focus();}}});
 }
 function nav(){const bar=$('.v2-topbar');if(!bar)return;const brand=document.createElement('a');brand.href='index.html';brand.className='ed-brand';brand.textContent='史料 · 研究';bar.prepend(brand);
   bar.prepend(btn('☰',()=>{if(innerWidth>992){document.body.classList.toggle('ed-nav-collapsed');}else{const sidebar=$('#v2-sidebar'),overlay=$('#v2-sidebar-overlay');sidebar?.classList.toggle('open');overlay?.classList.toggle('visible',sidebar?.classList.contains('open'));}},'icon-btn ed-desktop-toggle'));
   const actions=document.createElement('div');actions.className='ed-top-actions';const network=document.createElement('span');network.className='ed-sync';const refresh=()=>network.textContent=navigator.onLine?'研究工作台':'离线 · 草稿保存在本机';refresh();window.addEventListener('online',()=>{refresh();syncDraft();});window.addEventListener('offline',refresh);actions.append(network,btn('紧凑',()=>{document.body.classList.toggle('ed-compact');localStorage.setItem('research-compact',JSON.stringify(document.body.classList.contains('ed-compact')));},'ed-density'),btn('新增史料',()=>showForm(),'ed-primary'));bar.append(actions);document.body.classList.toggle('ed-compact',safeRead('research-compact',false));
   const tabs=document.createElement('div');tabs.className='ed-view-tabs';tabs.setAttribute('aria-label','浏览视图');$$('.v2-nav-view').forEach(item=>{const label=item.textContent.replace(item.querySelector('.material-icons')?.textContent||'','').trim().replace('Word ','');const b=btn(label,()=>item.click());b.dataset.view=item.dataset.view;tabs.append(b);});$('.v2-workspace-chrome').append(tabs);
   const views=$('.v2-nav-view')?.closest('.v2-nav-section');if(views)views.hidden=true;
   const more=$('.v2-nav-item[data-action="types"]')?.closest('.v2-nav-section');if(more){const d=document.createElement('details');d.className='ed-nav-group';const sum=document.createElement('summary');sum.textContent='研究工具与管理';d.append(sum);more.before(d);d.append(more);}
   const maintenance=document.createElement('details');maintenance.className='ed-nav-group';maintenance.innerHTML='<summary>高级维护</summary>';['migrate','codes','duplicates'].forEach(a=>{const b=$(`[data-action="${a}"]`);if(b)maintenance.append(b);});$('#v2-sidebar').append(maintenance);
   const localButton=btn('本机恢复草稿',()=>localDrafts().catch(e=>toast(e.message)),'v2-nav-item');$('[data-nav="recent"]')?.after(localButton);
   const results=document.createElement('div');results.className='ed-results';results.setAttribute('aria-live','polite');$('.v2-workspace-chrome').append(results);
   let queued=false;function update(){queued=false;let list=[];try{list=getFilteredEntries();}catch{}results.replaceChildren();const count=document.createElement('span');count.textContent=`${list.length.toLocaleString()} 条史料`;results.append(count);const query=$('#search-input')?.value.trim();if(query){const chip=btn('搜索：'+query+' ×',()=>{const i=$('#search-input');i.value='';i.dispatchEvent(new Event('input',{bubbles:true}));});chip.className='ed-chip';results.append(chip);}['startDate','endDate'].forEach((id,i)=>{const v=$('#'+id)?.value;if(v){const chip=btn((i?'截至 ':'始于 ')+v+' ×',()=>{$('#'+id).value='';applyAdvancedSearch();});chip.className='ed-chip';results.append(chip);}});if(!list.length&&query)results.append(btn('清除筛选',()=>{clearAdvancedSearch();const q=$('#search-input');q.value='';q.dispatchEvent(new Event('input',{bubbles:true}));}));tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===(typeof currentViewMode!=='undefined'?currentViewMode:'list'))));}
   const wrapper=$('#entries-container');if(wrapper)new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(()=>{update();highlightResults();});}}).observe(wrapper,{childList:true,subtree:true});document.addEventListener('input',e=>{if(e.target.id==='search-input')setTimeout(()=>{update();highlightResults();},300);});update();
   const reading=document.createElement('div');reading.className='ed-reading-tools';let size=safeRead('research-read-size',18);const apply=()=>{document.documentElement.style.setProperty('--read-size',size+'px');localStorage.setItem('research-read-size',JSON.stringify(size));};reading.append(btn('A−',()=>{size=Math.max(14,size-1);apply();}),btn('A＋',()=>{size=Math.min(26,size+1);apply();}));apply();actions.prepend(reading);
 }
 function highlightResults(){const query=$('#search-input')?.value.trim().toLowerCase()||'';$$('#entries-container .entry-item,#entries-container .card-entry').forEach(row=>{if(row.dataset.edHighlight===query)return;row.dataset.edHighlight=query;row.querySelectorAll('mark.ed-match').forEach(m=>m.replaceWith(document.createTextNode(m.textContent)));row.querySelectorAll('.ed-match-source').forEach(n=>n.remove());row.normalize();if(!query)return;const entry=(typeof entries!=='undefined'?entries:[]).find(e=>e.id===row.dataset.id);if(entry){const fields=[['标题',entry.title],['原文',new DOMParser().parseFromString(entry.content||'','text/html').body.textContent],['分析',new DOMParser().parseFromString(entry.analysis||'','text/html').body.textContent],['来源',entry.citation]];const labels=fields.filter(([,t])=>String(t||'').toLowerCase().includes(query)).map(([label])=>label);if(labels.length){const badge=document.createElement('small');badge.className='ed-match-source';badge.textContent='匹配：'+labels.join('、');row.append(badge);}}
  row.querySelectorAll('.entry-title,.card-entry-title,.card-entry-excerpt,.v2-entry-citation').forEach(root=>{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];let n;while(n=walker.nextNode())if(!n.parentElement.closest('button,.material-icons'))nodes.push(n);nodes.forEach(n=>{const value=n.textContent;let at=0,i;const fragment=document.createDocumentFragment();while((i=value.toLowerCase().indexOf(query,at))>=0){fragment.append(document.createTextNode(value.slice(at,i)));const m=document.createElement('mark');m.className='ed-match';m.textContent=value.slice(i,i+query.length);fragment.append(m);at=i+query.length;}if(at){fragment.append(document.createTextNode(value.slice(at)));n.replaceWith(fragment);}});});});}
 function setupHome(){document.body.classList.add('ed-home');const h=document.createElement('header');h.className='ed-masthead';h.innerHTML='<div class="ed-eyebrow">THE RESEARCH ARCHIVE</div><a href="index.html">史料 · 研究</a><p>整理历史的片段，建立思想的联系。</p>';document.body.prepend(h);const title=$('.page-title');if(title)title.textContent='我的研究课题';const tabs=document.createElement('div');tabs.className='ed-home-tabs';[['all','全部课题'],['recent','最近使用'],['archived','已归档']].forEach(([v,label])=>{const b=btn(label,()=>{window.researchProjectFilter=v;tabs.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderProjects();});b.dataset.filter=v;b.setAttribute('aria-pressed',String(v==='all'));tabs.append(b);});tabs.append(btn('目录 / 专题卡片',()=>document.body.classList.toggle('ed-project-cards')));$('#projectList')?.before(tabs);
  let searchTimer;$('#searchInput')?.addEventListener('input',e=>{if(e.isComposing)return;clearTimeout(searchTimer);searchTimer=setTimeout(applyFilter,250);});
  const latest=safeRead('research-last-project',null);if(latest){const row=document.createElement('div');row.className='ed-continue';const t=document.createElement('span');t.textContent='继续上次研究';const a=document.createElement('a');a.href='database.html?project='+encodeURIComponent(latest.id);a.textContent=latest.title;row.append(t,a);$('.stats-grid')?.before(row);}
 }
 function restoreView(){const key='research-view/'+scope();const saved=safeRead(key,null);if(saved?.mode)changeViewMode(saved.mode);if(saved?.query){$('#search-input').value=saved.query;$('#search-input').dispatchEvent(new Event('input',{bubbles:true}));}let scrollTimer;const el=$('#entries-container-wrapper');if(el){if(saved?.scroll)el.scrollTop=saved.scroll;el.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>localStorage.setItem(key,JSON.stringify({mode:currentViewMode,query:$('#search-input')?.value||'',scroll:el.scrollTop})),200);});}document.addEventListener('click',e=>{if(e.target.closest('.ed-view-tabs'))setTimeout(()=>localStorage.setItem(key,JSON.stringify({mode:currentViewMode,query:$('#search-input')?.value||'',scroll:el?.scrollTop||0})),100);});}
 document.addEventListener('DOMContentLoaded',()=>{const skip=document.createElement('a');skip.className='ed-skip';skip.href=$('.v2-main')?'#workspace-main':'#projectList';skip.textContent='跳到主要内容';document.body.prepend(skip);if($('.v2-main')){$('.v2-main').id='workspace-main';nav();setupEditor();const title=$('#v2-project-title');if(title)new MutationObserver(()=>{if(title.textContent&&!title.textContent.includes('加载'))localStorage.setItem('research-last-project',JSON.stringify({id:new URL(location.href).searchParams.get('project')||localStorage.getItem('currentProject'),title:title.textContent}));}).observe(title,{childList:true,characterData:true,subtree:true});}else if($('#projectList'))setupHome();else document.body.classList.add('ed-login');
   $$('button[title]:not([aria-label])').forEach(b=>b.setAttribute('aria-label',b.title));
   if($('.v2-main')){window.deleteEntry=deleteWithUndo;document.addEventListener('research-data-ready',()=>{restoreView();const id=new URL(location.href).searchParams.get('entry');if(id&&entries.some(e=>e.id===id)){changeViewMode('word');V2Word.setActiveEntry(id);}}, {once:true});}
 });
 window.addEventListener('storage',e=>{if(e.key==='research-save-signal'&&active&&dirty)status('另一窗口有保存操作，请留意版本冲突');});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&dirty)persistLocal();});
 window.ResearchWorkspace={opened,close,saveEntry,syncDraft,persistLocal,changed,isDirty:()=>active&&dirty,toast,restoreView,continueCloudDraft};
})();
