const {chromium}=require('playwright');
const fs=require('fs');
fs.mkdirSync('tests/results',{recursive:true});
const assert=require('node:assert/strict');
(async()=>{
const server=require('../scripts/serve.cjs').createServer();await new Promise(resolve=>server.listen(8765,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:process.env.BROWSER_CHANNEL||'msedge'}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
await context.route(/^https?:\/\/(?!127\.0\.0\.1)/,route=>route.fulfill({status:200,body:'',contentType:route.request().resourceType()==='stylesheet'?'text/css':'application/javascript'}));
await context.addInitScript(()=>{
 const sample={id:'19370707-01',title:'卢沟桥事变：报刊记载与地方档案',date:'1937-07-07',content:'<h2>史料摘录</h2><p>历史研究始于对材料的细读。报刊记录呈现了事件发生时的社会视角，也留下了值得追问的空白。</p><blockquote><p>比较不同来源，才能理解同一事件的多重面貌。</p></blockquote><p><strong>材料说明：</strong>这里是用于界面验证的示例内容，并非真实史料。</p>',analysis:'<p>比较报刊与档案的叙述差异，关注时间、地域与作者立场。</p>',keywords:['近代史','报刊','社会记忆'],typeId:'general',metadata:{author:'研究示例'},createdAt:1700000000000,updatedAt:1700000000000,events:[{id:'ev1',date:'1937-07-07',description:'示例事件：史料记载的时间节点'}],comments:{}};
 const second={...sample,id:'19380000-02',title:'城市空间与日常生活的变迁',date:'1938',keywords:['城市史','日常生活'],events:[{id:'ev2',date:'1938-01-01',description:'研究线索：城市社会的变化'}]};
 const third={...sample,id:'19390000-03',title:'地方文献中的社会网络',date:'约1939',keywords:['地方志','社会网络'],events:[]};
 const store={users:{test:{profile:{displayName:'研究者'},projects:{demo:{id:'demo',name:'近代中国的社会与记忆',description:'从报刊、档案与地方文献出发，探索历史的多重叙述。',createdAt:1700000000000,updatedAt:Date.now(),entries:{[sample.id]:sample,[second.id]:second,[third.id]:third}}}}}};
 const callbacks=[];const clone=x=>x===undefined?null:JSON.parse(JSON.stringify(x));
 const parts=p=>p.split('/').filter(Boolean);const get=p=>parts(p).reduce((o,k)=>o?.[k],store)??null;
 function set(p,v){const path=parts(p);let o=store;path.slice(0,-1).forEach(k=>{if(!o[k])o[k]={};o=o[k];});if(v===null)delete o[path.at(-1)];else o[path.at(-1)]=clone(v);callbacks.forEach(c=>{if(p.startsWith(c.p)||c.p.startsWith(p))setTimeout(()=>c.fn(snap(get(c.p))),0);});}
 const snap=v=>({val:()=>clone(v),exists:()=>v!==null,numChildren:()=>Object.keys(v||{}).length,forEach:fn=>Object.entries(v||{}).forEach(([key,value])=>fn({...snap(value),key}))});
 function ref(p=''){return {key:parts(p).at(-1),child:k=>ref(p+'/'+k),once:async()=>snap(get(p)),get:async()=>snap(get(p)),on:(ev,fn)=>{callbacks.push({p,fn});setTimeout(()=>fn(snap(get(p))),25);return fn;},off:()=>{},set:async v=>set(p,v),update:async patch=>Object.entries(patch).forEach(([k,v])=>set(p+'/'+k,v)),remove:async()=>set(p,null),transaction:async fn=>{const v=fn(clone(get(p)));if(v===undefined)return{committed:false,snapshot:snap(get(p))};set(p,v);return{committed:true,snapshot:snap(v)};},orderByKey(){return this},orderByChild(){return this},startAt(){return this},endAt(){return this},limitToLast(){return this},push:()=>ref(p+'/'+Math.random().toString(36).slice(2))};}
 const user={uid:'test',displayName:'研究者',email:'research@example.test',emailVerified:true};const auth={currentUser:user,onAuthStateChanged:fn=>{setTimeout(()=>fn(user),20);return()=>{};},signOut:async()=>{}};const db={ref};function database(){return db}database.ServerValue={TIMESTAMP:Date.now()};window.firebase={apps:[],initializeApp(){this.apps.push({});return{};},app:()=>({}),auth:()=>auth,database};window.__test={store,ref};
 localStorage.setItem('currentProject','demo');window.confirm=()=>false;
});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());
await page.goto('http://127.0.0.1:8765/database.html?project=demo');await page.waitForTimeout(1700);
await page.screenshot({path:'tests/results/database-desktop.png',fullPage:true});
await page.locator('.ed-top-actions .ed-primary').click();await page.waitForSelector('.tiptap');await page.waitForTimeout(400);
await page.locator('#entry-form [name="title"]').fill('编辑器功能验证');await page.locator('#entry-form [name="date"]').fill('1937年7月7日');await page.locator('#entry-form [name="date"]').press('Tab');await page.locator('#entry-form [name="keywords"]').fill('验证');
assert.equal(await page.locator('#entry-form [name="date"]').inputValue(),'1937-07-07');
await page.locator('#entry-form [name="date"]').fill('1937-02-30');assert.equal(await page.locator('#entry-form [name="date"]').evaluate(e=>e.checkValidity()),false);await page.locator('#entry-form [name="date"]').fill('1937-07-07');
await page.locator('#editor-container .tiptap').fill('研究材料与分析。');
await page.screenshot({path:'tests/results/editor-desktop.png',fullPage:true});
await page.evaluate(()=>quill.editor.chain().focus('end').insertTable({rows:3,cols:3,withHeaderRow:true}).run());
console.log('TABLE',await page.locator('#editor-container table').count());
assert.equal(await page.locator('#editor-container table').count(),1);
assert.equal(await page.evaluate(()=>{const html='<h2>标题</h2><p class="ql-align-center"><span class="ql-font-KaiTi" style="color: rgb(122, 48, 45)"><strong>旧内容</strong></span><sup>2</sup></p><table><tr><td>单元格</td></tr></table><script>window.bad=true</script>';const x=new ResearchEditor('#log-editor-container');x.setHTML(html);const result=x.getHTML();return result.includes('旧内容')&&result.includes('table')&&result.includes('text-align: center')&&result.includes('KaiTi')&&!result.includes('<script');}),true);
assert.equal(await page.evaluate(()=>{const e=window.analysisQuill;e.editor.commands.setContent('<p>分析</p>');e.editor.chain().focus('end').insertContent({type:'researchNote',attrs:{text:'示例出处，第12页',kind:'文献出处'}}).setImage({src:'https://example.test/image.png',caption:'图注：示例档案',width:'50%'}).run();const html=e.getHTML();e.setHTML(html);return e.getHTML().includes('data-note')&&e.getHTML().includes('图注：示例档案')&&e.editor.state.doc.childCount===3;}),true);
assert.equal(await page.evaluate(()=>window.analysisQuill.editor.can().undo()),false,'loading a document must reset undo history');

// Formatting and annotations must preserve selected source text through reload.
await page.evaluate(()=>{quill.setHTML('<p>保留原文用于注释验证</p>');quill.editor.commands.setTextSelection({from:1,to:5});});
await page.locator('#editor-container').getByRole('button',{name:'添加批注',exact:true}).click();
await page.locator('dialog textarea[name="text"]').fill('第一条注释');
await page.locator('dialog button[type="submit"]').click();
assert.equal(await page.evaluate(()=>quill.editor.getText()),'保留原文用于注释验证');
assert.equal(await page.locator('#editor-container .ed-comment-marker').count(),1);
await page.locator('#editor-container .ed-comment-marker').click();
await page.locator('dialog textarea[name="text"]').fill('修订后的注释');
await page.locator('dialog textarea[name="reply"]').fill('编辑区的第一条回复');
await page.locator('dialog button[type="submit"]').click();
assert.equal(await page.locator('#editor-container .ed-comment-marker').getAttribute('title'),'修订后的注释');
await page.evaluate(()=>{quill.setHTML(quill.getHTML());quill.editor.commands.setTextSelection({from:1,to:5});});
await page.locator('#editor-container select[aria-label="字体"]').selectOption('KaiTi');
await page.locator('#editor-container select[aria-label="字号"]').selectOption('24px');
await page.locator('#editor-container').getByRole('button',{name:'高亮设置',exact:true}).click();
await page.locator('.ed-color-popover').getByRole('button',{name:'浅黄',exact:true}).click();
assert.ok(await page.evaluate(()=>quill.getHTML().includes('KaiTi')&&quill.getHTML().includes('24px')&&quill.getHTML().includes('mark')));
assert.equal(await page.locator('#editor-container .research-prose').evaluate(e=>getComputedStyle(e).overflowY),'scroll');
await page.evaluate(()=>quill.editor.chain().focus('end').insertTable({rows:2,cols:2}).run());
await page.evaluate(()=>V2Knowledge.addRelation('19370707-01','19380000-02','double'));
assert.equal(await page.evaluate(()=>V2Knowledge.buildGraph(entries).links.filter(l=>l.bidirectional).length),1);
await page.evaluate(()=>V2Knowledge.openEntry('19380000-02'));
await page.waitForSelector('.research-comparison');
assert.ok(await page.locator('.research-comparison').innerText().then(t=>t.includes('城市空间')));
await page.locator('.research-comparison [data-close]').click();
console.log('PASS: selection preserved, note editing, format controls, scrollbars, reciprocal links and comparison.');

await page.locator('#entry-form button[type="submit"]').click();await page.waitForTimeout(700);
assert.equal(await page.evaluate(()=>Object.keys(__test.store.users.test.projects.demo.entries).length),4);
assert.equal(await page.locator('#entry-form').isVisible(),false);
const annotatedId=await page.evaluate(()=>entries.find(e=>e.title==='编辑器功能验证').id);
await page.locator('.ed-view-tabs button[data-view="word"]').click();
await page.evaluate(id=>V2Word.setActiveEntry(id),annotatedId);await page.waitForTimeout(300);
assert.ok(await page.locator('#word-notes-list').innerText().then(t=>t.includes('修订后的注释')&&t.includes('编辑区的第一条回复')));
const cid=await page.evaluate(id=>V2Comments.commentsOf(entries.find(e=>e.id===id)).find(c=>c.text==='修订后的注释').id,annotatedId);
await page.evaluate(async({id,cid})=>{await V2Comments.addReply(id,cid,'来自阅读视图的回复');V2Word.refresh();},{id:annotatedId,cid});
await page.evaluate(id=>editEntry(id),annotatedId);await page.waitForTimeout(300);
await page.locator('#editor-container .ed-comment-marker').click();
assert.ok(await page.locator('dialog .ed-comment-replies').innerText().then(t=>t.includes('来自阅读视图的回复')));
await page.screenshot({path:'tests/results/shared-comment-thread.png',fullPage:true});
await page.locator('dialog textarea[name="reply"]').fill('第二条编辑回复');
await page.locator('dialog button[type="submit"]').click();
// A concurrent reply must survive merging the editor draft.
await page.evaluate(({id,cid})=>V2Comments.addReply(id,cid,'其他窗口的回复'),{id:annotatedId,cid});
await page.locator('#entry-form button[type="submit"]').click();await page.waitForTimeout(350);
assert.equal(await page.evaluate(({id,cid})=>V2Comments.commentsOf(entries.find(e=>e.id===id)).find(c=>c.id===cid).replies.length,{id:annotatedId,cid}),4);
console.log('PASS: editor/reader shared comment threads and concurrent reply preservation.');
await page.evaluate(()=>editEntry('19370707-01'));await page.waitForTimeout(500);
await page.evaluate(()=>V2Knowledge.openEntry('19380000-02'));
await page.waitForSelector('.research-comparison');
await page.screenshot({path:'tests/results/related-comparison.png',fullPage:true});
await page.locator('.research-comparison [data-edit]').click();
await page.waitForTimeout(400);
assert.equal(await page.locator('#entry-form [name="title"]').inputValue(),'城市空间与日常生活的变迁');
assert.equal(await page.locator('.research-comparison').count(),0);
assert.equal(await page.locator('#entry-form').isVisible(),true);
await page.evaluate(()=>hideForm());await page.waitForTimeout(250);
await page.evaluate(()=>V2Knowledge.show());
const before=await page.locator('.v2-kg-node circle').first().getAttribute('cx');
await page.waitForTimeout(200);
assert.notEqual(await page.locator('.v2-kg-node circle').first().getAttribute('cx'),before);
assert.equal(await page.locator('.v2-kg-link.is-double').count(),1);
const graphSpacing=await page.evaluate(()=>{const nodes=[...document.querySelectorAll('.v2-kg-node')];const points=nodes.map(n=>{const c=n.querySelector('circle');return {x:+c.getAttribute('cx'),y:+c.getAttribute('cy')}});let minimum=Infinity;for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++)minimum=Math.min(minimum,Math.hypot(points[i].x-points[j].x,points[i].y-points[j].y));return {minimum,labelLines:nodes.map(n=>n.querySelectorAll('text tspan').length),titles:nodes.map(n=>n.querySelector('title')?.textContent)};});
assert.ok(graphSpacing.minimum>90,'knowledge graph nodes are too close together');
assert.ok(graphSpacing.labelLines.every(lines=>lines>=1&&lines<=2),'knowledge graph labels should wrap to at most two lines');
assert.ok(graphSpacing.titles.every(Boolean),'knowledge graph nodes should retain their full title');
await page.screenshot({path:'tests/results/knowledge-enhanced.png',fullPage:true});
await page.evaluate(()=>V2Knowledge.hide());await page.waitForTimeout(250);
await page.evaluate(()=>editEntry('19370707-01'));await page.waitForTimeout(300);
console.log('PASS: comparison edit transition and animated bidirectional graph.');
console.log('EDIT-EXISTING',await page.evaluate(()=>({title:document.querySelector('#entry-form [name="title"]').value,content:quill.getHTML().slice(0,100)})));
await page.screenshot({path:'tests/results/edit-existing.png',fullPage:true});
await page.locator('#entry-form [name="title"]').fill('已修订的史料标题');await page.locator('#entry-form button[type="submit"]').click();await page.waitForTimeout(400);
assert.equal(await page.evaluate(()=>__test.store.users.test.projects.demo.entries['19370707-01'].revision),1);
assert.equal(await page.evaluate(()=>__test.store.users.test.projects.demo.entries['19370707-01']._history.length),1);
await page.evaluate(()=>editEntry('19370707-01'));await page.waitForTimeout(300);
await page.locator('#entry-form [name="title"]').fill('本机冲突修改');await page.evaluate(()=>__test.ref('users/test/projects/demo/entries/19370707-01').update({revision:2,title:'另一窗口的修改'}));
await page.locator('#entry-form button[type="submit"]').click();await page.waitForTimeout(300);
assert.equal(await page.evaluate(()=>__test.store.users.test.projects.demo.entries['19370707-01'].title),'另一窗口的修改');
assert.equal(await page.locator('#entry-form').isVisible(),true);
await page.locator('.ed-toast button').click();await page.getByRole('button',{name:'载入云端版本',exact:true}).click();await page.waitForTimeout(250);
await page.locator('#entry-form .ed-editor-actions').getByRole('button',{name:'历史版本',exact:true}).click();await page.getByRole('button',{name:'恢复到编辑区',exact:true}).click();await page.waitForTimeout(250);
assert.equal(await page.locator('#entry-form [name="title"]').inputValue(),'卢沟桥事变：报刊记载与地方档案');
await page.locator('#entry-form button[type="submit"]').click();await page.waitForTimeout(400);
await page.evaluate(()=>editEntry('19370707-01'));await page.waitForTimeout(250);
await context.setOffline(true);await page.locator('#entry-form [name="title"]').fill('离线恢复验证');await page.evaluate(()=>ResearchWorkspace.persistLocal());await page.evaluate(()=>hideForm());await page.waitForTimeout(200);await context.setOffline(false);
await page.getByRole('button',{name:'本机恢复草稿',exact:true}).click();await page.locator('.ed-version').filter({hasText:'离线恢复验证'}).getByRole('button',{name:'恢复',exact:true}).click();await page.waitForTimeout(350);
assert.equal(await page.locator('#entry-form [name="title"]').inputValue(),'离线恢复验证');
await page.locator('#entry-form [name="date"]').fill('1937-02-30');await page.evaluate(()=>hideForm());await page.waitForTimeout(100);await page.evaluate(()=>editEntry('19370707-01'));await page.waitForTimeout(250);
assert.equal(await page.locator('#entry-form [name="date"]').evaluate(e=>e.checkValidity()),true,'a previous invalid draft must not poison a different document');
await page.locator('#entry-form .ed-calendar-button').first().click();await page.locator('.calendar-year').fill('1900');await page.locator('.calendar-month').selectOption('2');assert.equal(await page.locator('.ed-calendar-days button').count(),28);await page.getByRole('button',{name:'1900年2月28日',exact:true}).click();assert.equal(await page.locator('#entry-form [name="date"]').inputValue(),'1900-02-28');
await page.locator('#entry-form [name="date"]').fill('1937-07-07');
const exported=await page.evaluate(()=>({json:JSON.parse(V2Export.toJSON(entries)),html:V2Export.toHTML(entries,false)}));assert.equal(exported.json.entries.length,4);assert.ok(exported.json.entries.some(e=>e.contentDocument));assert.ok(exported.html.includes('<table'));assert.ok(exported.html.includes('data-note'));
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tests/results/editor-mobile.png',fullPage:true});
await page.evaluate(()=>hideForm());await page.waitForTimeout(400);await page.screenshot({path:'tests/results/database-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);
await page.locator('#search-input').fill('地方文献');await page.waitForTimeout(450);assert.ok(await page.locator('.ed-results').innerText().then(t=>t.includes('1 条史料')));await page.locator('#search-input').fill('');await page.waitForTimeout(350);
await page.setViewportSize({width:1440,height:1000});await page.locator('.ed-view-tabs button[data-view="word"]').click();await page.waitForTimeout(300);await page.screenshot({path:'tests/results/reading-desktop.png',fullPage:true});
await page.locator('.ed-view-tabs button[data-view="timeline"]').click();await page.waitForTimeout(300);assert.equal(await page.locator('#ed-timeline-year').count(),1);await page.screenshot({path:'tests/results/timeline-desktop.png',fullPage:true});
// A recovered shared draft is removed only if no one has updated it since recovery.
await page.evaluate(async()=>{const entry=__test.store.users.test.projects.demo.entries['19370707-01'];await db.ref(getProjectPath('drafts/recovery-check')).set({...entry,originalId:entry.id,baseRevision:entry.revision,baseUpdatedAt:entry.updatedAt});await ResearchWorkspace.continueCloudDraft('recovery-check');});await page.waitForTimeout(250);
await page.locator('#entry-form button[type="submit"]').click();await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>__test.store.users.test.projects.demo.drafts?.['recovery-check']??null),null);
await page.evaluate(async()=>{const entry=__test.store.users.test.projects.demo.entries['19370707-01'];await db.ref(getProjectPath('drafts/recovery-check')).set({...entry,originalId:entry.id,baseRevision:entry.revision,baseUpdatedAt:entry.updatedAt});await ResearchWorkspace.continueCloudDraft('recovery-check');});await page.waitForTimeout(250);
await page.evaluate(()=>db.ref(getProjectPath('drafts/recovery-check')).update({updatedAt:Date.now()+10000,title:'另一个窗口的新草稿'}));await page.locator('#entry-form button[type="submit"]').click();await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>__test.store.users.test.projects.demo.drafts['recovery-check'].title),'另一个窗口的新草稿');
console.log('PASS: recovered cloud draft cleanup preserves concurrent changes.');
// Correcting an entry date must migrate its generated ID and every inbound relation.
await page.evaluate(()=>editEntry('19370707-01'));await page.waitForTimeout(250);
await page.locator('#entry-form [name="date"]').fill('1937-07-08');
await page.locator('#entry-form button[type="submit"]').click();await page.waitForTimeout(400);
assert.equal(await page.evaluate(()=>__test.store.users.test.projects.demo.entries['19370707-01']??null),null);
assert.equal(await page.evaluate(()=>__test.store.users.test.projects.demo.entries['19370708-01'].id),'19370708-01');
assert.equal(await page.evaluate(()=>__test.store.users.test.projects.demo.entries['19370708-01'].date),'1937-07-08');
assert.ok(await page.evaluate(()=>__test.store.users.test.projects.demo.entries['19380000-02'].relatedSources.includes('19370708-01')));
assert.equal(await page.evaluate(()=>__test.store.users.test.projects.demo.entries['19380000-02'].relatedSources.includes('19370707-01')),false);
console.log('PASS: corrected dates migrate entry IDs and inbound knowledge relations.');
await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8765/index.html');await page.waitForTimeout(900);await page.screenshot({path:'tests/results/home-desktop.png',fullPage:true});console.log('FINAL ERRORS',JSON.stringify(errors));
assert.deepEqual(errors,[]);console.log('PASS: date validation, editor conversion, table, notes/image roundtrip, create, revision history, conflict protection, history restore, mobile layout, search, reading and timeline.');
const loginContext=await browser.newContext({viewport:{width:1280,height:900}});await loginContext.route(/^https?:\/\/(?!127\.0\.0\.1)/,route=>route.fulfill({status:200,body:''}));await loginContext.addInitScript(()=>{window.firebase={initializeApp:()=>({}),auth:()=>({currentUser:null,onAuthStateChanged:fn=>setTimeout(()=>fn(null),10)})};});const login=await loginContext.newPage();await login.goto('http://127.0.0.1:8765/login.html');await login.waitForTimeout(400);await login.screenshot({path:'tests/results/login-desktop.png',fullPage:true});await login.setViewportSize({width:390,height:844});await login.screenshot({path:'tests/results/login-mobile.png',fullPage:true});assert.equal(await login.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);console.log('PASS: offline draft recovery, calendar leap-year navigation, reset validity, lossless JSON/HTML export, login layouts.');
await browser.close();
server.close();
})().catch(e=>{console.error(e);process.exit(1)});


