// Local demo data only. Never loaded by production HTML.
(function(){
 const sample={id:'19370707-01',title:'卢沟桥事变：报刊记载与地方档案',date:'1937-07-07',content:'<h2>史料摘录</h2><p>历史研究始于对材料的细读。报刊记录呈现了事件发生时的社会视角，也留下了值得追问的空白。</p><blockquote><p>比较不同来源，才能理解同一事件的多重面貌。</p></blockquote><p><strong>材料说明：</strong>这里是用于界面验证的示例内容，并非真实史料。</p>',analysis:'<p>比较报刊与档案的叙述差异，关注时间、地域与作者立场。</p>',keywords:['近代史','报刊','社会记忆'],typeId:'general',metadata:{author:'研究示例'},createdAt:1700000000000,updatedAt:1700000000000,events:[{id:'ev1',date:'1937-07-07',description:'示例事件：史料记载的时间节点'}],comments:{}};
 const second={...sample,id:'19380000-02',title:'城市空间与日常生活的变迁',date:'1938',keywords:['城市史','日常生活'],events:[{id:'ev2',date:'1938-01-01',description:'研究线索：城市社会的变化'}]};
 const third={...sample,id:'19390000-03',title:'地方文献中的社会网络',date:'约1939',keywords:['地方志','社会网络'],events:[]};
 const store={users:{test:{profile:{displayName:'研究者'},projects:{demo:{id:'demo',name:'近代中国的社会与记忆',description:'从报刊、档案与地方文献出发，探索历史的多重叙述。',createdAt:1700000000000,updatedAt:Date.now(),entries:{[sample.id]:sample,[second.id]:second,[third.id]:third}}}}}};
 try { const saved = JSON.parse(sessionStorage.getItem('research-demo-store') || 'null'); if (saved?.users) store.users = saved.users; } catch {}
 if (!store.users.test.projects.letters) store.users.test.projects.letters = {id:'letters', name:'书信中的知识与交往',description:'以私人书信与日记为线索，观察近代知识分子的思想交流。',tags:['书信','思想史'],createdAt:1705000000000,updatedAt:Date.now()-86400000,entries:{}};
 if (!store.users.test.projects.local) store.users.test.projects.local = {id:'local',name:'地方志与区域社会',description:'地方文献的整理、互证与地理关联。',tags:['地方志','区域史'],createdAt:1690000000000,updatedAt:Date.now()-86400000*6,entries:{}};
 const callbacks=[];const clone=x=>x===undefined?null:JSON.parse(JSON.stringify(x));
 const parts=p=>p.split('/').filter(Boolean);const get=p=>parts(p).reduce((o,k)=>o?.[k],store)??null;
 function set(p,v){const path=parts(p);let o=store;path.slice(0,-1).forEach(k=>{if(!o[k])o[k]={};o=o[k];});if(v===null)delete o[path.at(-1)];else o[path.at(-1)]=clone(v);try { sessionStorage.setItem('research-demo-store',JSON.stringify(store)); } catch {} callbacks.forEach(c=>{if(p.startsWith(c.p)||c.p.startsWith(p))setTimeout(()=>c.fn(snap(get(c.p))),0);});}
 const snap=v=>({val:()=>clone(v),exists:()=>v!==null,numChildren:()=>Object.keys(v||{}).length,forEach:fn=>Object.entries(v||{}).forEach(([key,value])=>fn({...snap(value),key}))});
 function ref(p=''){return {key:parts(p).at(-1),child:k=>ref(p+'/'+k),once:async()=>snap(get(p)),get:async()=>snap(get(p)),on:(ev,fn)=>{callbacks.push({p,fn});setTimeout(()=>fn(snap(get(p))),25);return fn;},off:()=>{},set:async v=>set(p,v),update:async patch=>Object.entries(patch).forEach(([k,v])=>set(p+'/'+k,v)),remove:async()=>set(p,null),transaction:async fn=>{const v=fn(clone(get(p)));if(v===undefined)return{committed:false,snapshot:snap(get(p))};set(p,v);return{committed:true,snapshot:snap(v)};},orderByKey(){return this},orderByChild(){return this},startAt(){return this},endAt(){return this},limitToLast(){return this},push:()=>ref(p+'/'+Math.random().toString(36).slice(2))};}
 const user={uid:'test',displayName:'研究者',email:'research@example.test',emailVerified:true};const auth={currentUser:user,onAuthStateChanged:fn=>{setTimeout(()=>fn(user),20);return()=>{};},signOut:async()=>{}};const db={ref};function database(){return db}database.ServerValue={TIMESTAMP:Date.now()};window.firebase={apps:[],initializeApp(){this.apps.push({});return{};},app:()=>({}),auth:()=>auth,database};window.__test={store,ref};
 localStorage.setItem('currentProject',new URL(location.href).searchParams.get('project')||'demo');
})();
