const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const server=require('../scripts/serve.cjs').createServer({demo:true});await new Promise(r=>server.listen(8769,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8769/database.html?project=demo');await page.waitForTimeout(700);
 await page.evaluate(()=>{entries=Array.from({length:156},(_,i)=>({...entries[0],id:'sample-'+i,title:'分页验证 '+String(i+1).padStart(3,'0')}));currentPage=15;renderEntries();});await page.evaluate(()=>document.fonts.ready);
 const pager=page.locator('#entry-pagination');await pager.screenshot({path:'tests/results/pagination-desktop.png'});assert.match(await pager.locator('.line-pager-total').innerText(),/156/);assert.deepEqual(await pager.locator('[data-page]').allTextContents(),['12','13','14','15','16']);await pager.getByRole('button',{name:'下一页',exact:true}).click();assert.equal(await page.evaluate(()=>currentPage),16);assert.equal(await pager.getByRole('button',{name:'下一页',exact:true}).isDisabled(),true);
 await pager.getByRole('button',{name:'上一页',exact:true}).click();assert.equal(await page.evaluate(()=>currentPage),15);await pager.locator('input').fill('5');await pager.locator('input').press('Enter');assert.equal(await page.evaluate(()=>currentPage),5);
 await pager.locator('input').fill('1.5');await pager.locator('input').press('Enter');assert.equal(await page.evaluate(()=>currentPage),5);assert.equal(await pager.locator('input').evaluate(e=>e.checkValidity()),false);
 await pager.locator('input').fill('999');await pager.locator('input').press('Enter');assert.equal(await page.evaluate(()=>currentPage),5);
 await pager.locator('input').fill('15');await pager.locator('input').press('Enter');await page.waitForTimeout(150);await pager.screenshot({path:'tests/results/pagination-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>renderEntries());await page.screenshot({path:'tests/results/pagination-mobile-full.png',fullPage:true});await pager.screenshot({path:'tests/results/pagination-mobile.png'});assert.ok(await pager.evaluate(e=>e.getBoundingClientRect().right<=innerWidth));
 await page.locator('.ed-view-tabs [data-view=word]').click();assert.equal(await page.locator('.word-toc-item').count(),156,'reading TOC must not lose items beyond the list page');assert.equal(await pager.isVisible(),false);
 await page.locator('.ed-view-tabs [data-view=list]').click();await page.locator('#search-input').fill('分页验证 002');await page.waitForTimeout(500);assert.match(await pager.locator('.line-pager-total').innerText(),/共 1 条/);assert.equal(await pager.getByRole('button',{name:'上一页',exact:true}).isDisabled(),true);assert.equal(await pager.getByRole('button',{name:'下一页',exact:true}).isDisabled(),true);
 await page.goto('http://127.0.0.1:8769/');await page.waitForTimeout(500);assert.equal(await page.locator('#project-pagination .line-pager-total').innerText(),'共 3 项');assert.equal(await page.locator('#project-pagination [aria-current=page]').innerText(),'1');
 assert.deepEqual(errors,[]);console.log('PASS: page window, last/previous page, valid/invalid jump, filtered count, mobile bounds, complete reading TOC and project pagination.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
